pipeline {
    agent any
    // tools {
    //     python 'deafult'
    // }

    options {
        timeout(time: 5, unit: 'MINUTES')
    }

    stages {
        stage('Start app and BD') {
            steps{
                powershell('cd API_integracion') 
                powershell('docker-compose up -d --build')
            }
        }
        stage('Stop app and BD') {
            steps{
                powershell('cd API_integracion') 
                powershell('docker-compose down')
            }
        }
    }
}